from __future__ import annotations


EPISODE_TITLES_EN = {
    1: "Proto-Indo-European Creation Myth: Manu and Yemo",
    2: "Yamnaya Migrations and the Spread of Indo-European Languages",
    3: "Horse Sacrifice in Ancient Indo-European Religion",
    4: "Trito, the Three-Headed Monster, and the Cattle-Raid Myth",
    5: "The Myth of Europa and the Origin of Europe's Name",
    6: "The Fall of Minoan Civilization and the Bronze Age Catastrophe",
    7: "The Bronze Age Collapse and the Sea Peoples",
    8: "The Trojan War Myth and the Politics of Heroes",
    9: "The Olympic Games and Rivalry among the Greek City-States",
    10: "Romulus and Remus: Rome's Founding Myth",
    11: "The Abduction of the Sabine Women",
    12: "Athenian Democracy: Light and Shadow",
    13: "The Birth of the Roman Republic",
    14: "The Persian Wars and Greek Identity",
    15: "The Peloponnesian War",
    16: "Alexander the Great and the Hellenistic World",
    17: "The Punic Wars and the Destruction of Carthage",
    18: "Gladiatorial Bloodsport and the Revolt of Spartacus",
    19: "Julius Caesar and the End of the Republic",
    20: "The Final Days of Cleopatra and Mark Antony",
    21: "Nero and the Great Fire of Rome",
    22: "The Jewish War and the Destruction of the Jerusalem Temple",
    23: "The Eruption of Vesuvius and Pompeii",
    24: "Trajan and the Paradox of Rome at Its Greatest Extent",
    25: "The Antonine Plague and the Marcomannic Wars",
    26: "The Edict of Caracalla and the Expansion of Roman Citizenship",
    27: "The Crisis of the Third Century and the Soldier Emperors",
    28: "The Mysterious Death of Emperor Carus",
    29: "Diocletian's Persecution and Christianity's Counterattack",
    30: "Constantine and the Council of Nicaea",
    31: "The Battle of Adrianople",
    32: "Alaric's Sack of Rome",
    33: "Attila the Hun and the Terror of Western Europe",
    34: "The Fall of the Western Roman Empire",
    35: "The Ostrogothic Kingdom and Theodoric the Great",
    36: "Clovis and the Frankish Kingdom",
    37: "Justinian's Wars of Reconquest",
    38: "The Nika Riots",
    39: "The Plague of Justinian",
    40: "The Lombard Conquest of Italy",
    41: "The Umayyad Conquest of Iberia and Al-Andalus",
    42: "The Battle of Tours and the Rise of the Franks",
    43: "The Donation of Pepin and the Birth of the Papal States",
    44: "The Raid on Lindisfarne and the Dawn of the Viking Age",
    45: "Charlemagne's Empire and the Saxon Wars",
    46: "Viking Slave Raids and Dublin",
    47: "The Treaty of Verdun and the Making of Western Europe's Borders",
    48: "Alfred the Great and the Danelaw",
    49: "The Magyar Settlement and the Birth of Hungary",
    50: "The Cadaver Synod and the Madness of the Papacy",
    51: "Rollo and the Duchy of Normandy",
    52: "The Battle of Lechfeld and Otto I",
    53: "The Birth of the Holy Roman Empire",
    54: "The Capetian Dynasty and the Long Rise of the French Monarchy",
    55: "Millennialism and the Fear of Heresy",
    56: "The Great Schism between East and West",
    57: "The Battle of Hastings and the Norman Conquest",
    58: "The Humiliation at Canossa and the Investiture Controversy",
    59: "The First Crusade and the Massacre of Jerusalem",
    60: "The Erfurt Latrine Disaster",
    61: "The Fourth Crusade and the Sack of Constantinople",
    62: "The Tragedy of the Children's Crusade",
    63: "Magna Carta and the Limits of Royal Power",
    64: "The Mongol Invasion of Europe",
    65: "Venice and Genoa: A Maritime Blood Feud",
    66: "The Fall of Acre and the End of the Crusader States",
    67: "The Fall of the Knights Templar",
    68: "The Great Famine and the Crisis of the Middle Ages",
    69: "Irish Traditions of Human Sacrifice and Royal Ritual",
    70: "The Opening of the Hundred Years' War",
    71: "The Black Death Arrives in Europe",
    72: "The Black Death and the Persecution of Jews",
    73: "Soaring Wages and the Liberation of Serfs after the Black Death",
    74: "The Jacquerie and the Collapse of French Society",
    75: "Wat Tyler and the English Peasants' Revolt",
    76: "The Battle of Agincourt and the Longbow",
    77: "The Burning of Joan of Arc",
    78: "The Fall of Constantinople",
    79: "Gutenberg's Printing Press and the Explosion of Knowledge",
    80: "The Wars of the Roses",
    81: "Isabella, Ferdinand, and the Unification of Spain",
    82: "Vlad the Impaler: The Real Model for Dracula",
    83: "Columbus and the Dawn of the Age of Exploration",
    84: "The Treaty of Tordesillas and the Division of the World",
    85: "The Italian Wars and the Fall of the City-States",
    86: "The Portuguese Maritime Empire and Violence in the Indian Ocean",
    87: "The Monster of Ravenna and Wartime Propaganda",
    88: "Martin Luther and the Ninety-Five Theses",
    89: "The Dancing Plague",
    90: "The German Peasants' War",
    91: "The Sack of Rome and the Shock to the Renaissance",
    92: "Henry VIII and the English Reformation",
    93: "The Council of Trent and the Counter-Reformation",
    94: "Habsburg Inbreeding and Dynastic Politics",
    95: "The Dutch War of Independence",
    96: "The St. Bartholomew's Day Massacre",
    97: "The Defeat of the Spanish Armada",
    98: "Witch Hunts and the Malleus Maleficarum",
    99: "The Legend of the Golem of Prague",
    100: "The Dark Side of European Folklore: Kelpies, Bastukai, and More",
    101: "The Legend of Elizabeth Bathory, the Blood Countess",
    102: "The Defenestration of Prague",
    103: "The Horrors of the Thirty Years' War",
    104: "The Height of the Witch Trials",
    105: "The Death of Gustavus Adolphus",
    106: "The Trial of Galileo",
    107: "Tulip Mania",
    108: "The English Civil War and the Execution of Charles I",
    109: "The Peace of Westphalia and the Sovereign State",
    110: "Cromwell's Campaign in Ireland",
    111: "The Great Fire of London",
    112: "The Ottoman Siege of Vienna",
    113: "The Glorious Revolution and Britain's Financial State",
    114: "Louis XIV and the Reality of Life at Versailles",
    115: "Peter the Great and the Great Northern War",
    116: "The War of the Spanish Succession",
    117: "The Acts of Union and the Birth of Great Britain",
    118: "The War of Jenkins' Ear",
    119: "The War of the Austrian Succession",
    120: "The Seven Years' War",
    121: "Public Debt and Britain's Fiscal-Military State",
    122: "The Partitions of Poland",
    123: "The French Revolution",
    124: "The Reign of Terror and the Guillotine",
    125: "The Irish Rebellion of 1798",
    126: "Napoleon's Coronation and the Destruction of Europe's Old Order",
    127: "Napoleon's Humiliating Rabbit Hunt",
    128: "The Peninsular War and Guerrilla Warfare",
    129: "Napoleon's Invasion of Russia",
    130: "Waterloo and the Vienna Settlement",
    131: "The Napoleonic Wars and the Awakening of Nationalism",
    132: "The Peterloo Massacre and the British Reform Movement",
    133: "The Industrial Revolution and Child Labor",
    134: "The Revolutionary Wave of 1830",
    135: "The Great Irish Famine",
    136: "The Revolutions of 1848",
    137: "The Crimean War",
    138: "London's Great Stink and the Sewer Revolution",
    139: "The Unification of Italy",
    140: "The Miracle of Liechtenstein's Army",
    141: "German Unification and the Franco-Prussian War",
    142: "The Paris Commune",
    143: "The Russian Empire and the Third Rome",
    144: "The Berlin Conference and the Scramble for Africa",
    145: "European Imperialism Unleashed",
    146: "The Balkan Wars and Europe's Powder Keg",
    147: "The Assassination at Sarajevo and the Trigger for World War I",
    148: "Trench Warfare in World War I",
    149: "The Armenian Genocide",
    150: "The Russian Revolution and the Collapse of the Eastern Front",
    151: "The Spanish Flu and Postwar Europe",
    152: "The Treaty of Versailles and the Postwar Order",
    153: "Mussolini and the Birth of Fascism",
    154: "Weimar Hyperinflation",
    155: "Hitler's Rise to Power and the Nazi Dictatorship",
    156: "The Spanish Civil War",
    157: "The Munich Agreement and the Sacrifice of Czechoslovakia",
    158: "The Invasion of Poland and the Outbreak of World War II",
    159: "The Fall of France and Dunkirk",
    160: "The Battle of Britain and the Blitz",
    161: "The Holocaust",
    162: "The German-Soviet War and the Eastern Front",
    163: "The Normandy Landings",
    164: "The Yalta Conference and the Iron Curtain",
    165: "The Berlin Blockade and Airlift",
    166: "The European Coal and Steel Community and the Treaties of Rome",
    167: "The Hungarian Revolution",
    168: "The Suez Crisis",
    169: "The Berlin Wall",
    170: "The Prague Spring",
    171: "The Chernobyl Nuclear Disaster",
    172: "The Fall of the Berlin Wall and the Revolutions of Eastern Europe",
    173: "The Collapse of the Soviet Union and a New Europe",
    174: "The Yugoslav Wars and Bosnia",
    175: "The Maastricht Treaty and the European Union",
    176: "The Eurozone Debt Crisis",
    177: "Brexit",
    178: "Russia's Invasion of Ukraine and the Remaking of European Security",
    179: "A Bloody History of Europe: Final Reckoning",
}


def english_episode_title(episode_number: int) -> str:
    title = EPISODE_TITLES_EN.get(int(episode_number))
    if not title:
        raise ValueError(f"missing English title for EP{int(episode_number):03d}")
    return title
