"""Narration-specific scene locks for Baekje episode 2, workbook rows 02-070..159."""

from __future__ import annotations


BAEKJE_EP02_REMAINING_COMMON_NEGATIVE_TERMS = (
    "person",
    "people",
    "human figure",
    "portrait",
    "face",
    "head",
    "body",
    "torso",
    "arm",
    "hand",
    "finger",
    "leg",
    "foot",
    "clothing",
    "modern suit",
    "modern coat",
    "modern hat",
    "modern shoes",
    "readable writing",
    "Chinese character",
    "Korean character",
    "Latin letter",
    "number",
    "inscription",
    "caption",
    "subtitle",
    "logo",
    "watermark",
    "signature",
    "modern vehicle",
    "motor",
    "engine",
    "propeller",
    "plastic",
    "electric light",
    "glass skyscraper",
    "fantasy armor",
    "black border",
    "dark vignette",
    "split panel",
    "collage",
)


BAEKJE_EP02_RITUAL_MEMORY_LOCKS: dict[str, tuple[str, str, str, str]] = {
    "더 놀라운 단서는 구태가 왕실 제사의 대상이었다는 기록입니다": (
        "02-070",
        "object-only royal-rite evidence with one elevated smooth ancestral marker on one state altar",
        "Strict overhead on pale bare wood: exactly one low square earth-brown clay state altar carries one smaller plain square top slab and one smooth featureless dark-red oval pebble marker centered above it",
        "natural wood and plain dark-red and earth-brown unglazed clay only",
    ),
    "책부원귀에는 백제가 도성에 구태의 사당을 세웠다고 적혀 있고": (
        "02-071",
        "object-only capital shrine evidence shown as one walled precinct with one roofless timber foundation",
        "High oblique view on bare earth: one rectangular rammed-earth precinct encloses exactly one plain roofless rectangular timber foundation platform at center, with an empty court and no standing walls or roof",
        "rammed earth, undecorated rough timber, and plain fired clay appropriate to early Baekje only",
    ),
    "왕이 해마다 네 차례 그 시조에게 제사를 지냈다는 내용도 전하죠": (
        "02-072",
        "object-only four-season royal rite cycle with one tray holding exactly four square ritual insets and one separate ancestor marker",
        "Strict overhead on uninterrupted pale earth-brown clay filling every edge: one pale square ritual tray holds exactly four identical reddish square clay insets arranged as one complete two-by-two grid, two upper and two lower with no empty cell; one solid smooth dark-red oval ancestor pebble rests alone above the tray",
        "plain pale earth-brown, reddish, and dark-red unglazed clay only",
    ),
    "단순한 외국의 소문이라면 국가 제사의 중심에 들어가기 어렵습니다": (
        "02-073",
        "object-only contrast between state ritual and one outside rumor pebble",
        "Strict overhead: one large smooth dark-red state-ritual disk rests at the exact center of one plain square earth-brown kingdom altar tile while one tiny smooth irregular natural-grey pebble remains far outside the tile across uninterrupted pale bare wood",
        "plain dark-red and earth-brown unglazed clay with one natural-grey stone pebble on pale natural wood only",
    ),
    "그래서 구태 전승 뒤에 실제 왕실 계보의 흔적이 있다고 보는 시선이 생깁니다": (
        "02-074",
        "object-only possible royal-lineage trace with one ancestor disk and three descendant markers",
        "Strict overhead on bare wood: one weathered grey ancestor disk touches a descending row of exactly three progressively smaller dark-red lineage disks, all blank and undecorated",
        "plain weathered grey and dark-red unglazed clay only",
    ),
    "하지만 그 기록을 옮긴 주석은 동명이 시조라는 쪽을 더 믿었고": (
        "02-075",
        "object-only preferred-founder judgment with one accepted red marker and exactly two excluded grey alternatives",
        "Strict overhead on pale bare wood: one large smooth red oval rests alone at the center of one narrow pale oblong clay strip; exactly one small grey triangle sits far left and exactly one small grey square sits far right on the bare wood, both outside the strip with clear gaps",
        "plain pale, red, and grey unglazed clay on natural wood only",
    ),
    "우태와 구태를 포함한 다른 계보에는 의심을 표시했습니다": (
        "02-076",
        "object-only doubted alternate genealogies with exactly two grey lineage disks behind one warning bar",
        "Strict overhead on uninterrupted earth-brown clay: exactly two separate grey lineage disks sit below one straight pale clay caution bar, with no contact and no marks",
        "plain earth-brown, grey, and pale unglazed clay only",
    ),
    "한 문장 안에서도 시조를 둘러싼 기억이 서로 밀어내고 있었던 셈이죠": (
        "02-077",
        "object-only competing founder memories pressing one blank record strip from opposite ends",
        "Strict overhead: one long blank pale clay record strip has one central fracture while one red disk presses its left end and one grey disk presses its right end",
        "plain pale, red, and grey unglazed clay on natural wood only",
    ),
    "왕실이 제사한 구태와 역사서가 내세운 온조는 어떻게 함께 존재했을까요": (
        "02-078",
        "object-only coexistence question represented by exactly two distinct founder-tradition markers",
        "Strict overhead in bright even daylight on uninterrupted pale bare wood filling every edge: exactly one smooth dark-red oval clay pebble and exactly one rough natural-grey rectangular stone fragment rest side by side with a clear gap on one plain earth-brown rectangular clay tile, every surface completely blank and featureless",
        "plain dark-red and earth-brown unglazed clay with one natural-grey stone fragment on pale natural wood only",
    ),
    "왕조 안에 서로 다른 집단의 조상 숭배가 겹쳐 있었을 수도 있고": (
        "02-079",
        "object-only overlapping ancestor traditions with exactly two colored ritual fields",
        "Strict overhead in bright even daylight on uninterrupted pale bare wood filling every edge: exactly two broad featureless flat clay ovals, one reddish and one grey-brown, overlap at center; no other object is present",
        "plain reddish and grey-brown unglazed clay on pale natural wood only",
    ),
    "후대 왕실이 여러 계보를 끌어안으며 정통성을 넓혔을 가능성도 있습니다": (
        "02-080",
        "object-only later royal consolidation with exactly three lineage markers enclosed by one kingdom tile",
        "Strict overhead in bright even daylight on uninterrupted pale bare wood filling every edge: one large shallow plain earth-brown rectangular kingdom tray contains exactly three separate smooth featureless oval clay pebbles in one straight horizontal row with equal gaps: one grey pebble at left, one brown pebble at center, and one dark-red pebble at right",
        "plain earth-brown, grey, brown, and dark-red unglazed clay on pale natural wood only",
    ),
    "그러나 가능성과 사실은 다르므로 여기서 단정하면 안 됩니다": (
        "02-081",
        "object-only separation of hypothesis from verified evidence",
        "Strict overhead on bare wood: one pale round hypothesis token remains far left and one dark-grey square evidence block remains far right across one broad empty gap, with no contact",
        "plain pale and dark-grey unglazed clay on natural wood only",
    ),
    "확실한 건 백제 사람들에게조차 기원의 기억이 하나가 아니었다는 점": (
        "02-082",
        "object-only multiple origin memories represented by exactly three distinct blank marker shapes",
        "Strict overhead on uninterrupted pale bare wood filling every edge: exactly three separate blank clay shapes form one straight horizontal row with wide equal gaps: one red circle at left, one grey oval at center, and one brown square at right; no base slab underneath",
        "plain red, grey, and brown unglazed clay on pale natural wood only",
    ),
    "그리고 그 기억들이 정치적 필요에 따라 다르게 강조됐다는 사실이죠": (
        "02-083",
        "object-only political emphasis with one enlarged red memory pebble and exactly two smaller grey alternatives",
        "Strict overhead in bright even daylight on uninterrupted pale earth-brown clay filling every edge: one large smooth red oval pebble rests on one low rounded clay mound at center while exactly two smaller smooth grey oval pebbles lie flat at equal distance on the left and right; every object is blank and featureless",
        "plain red, grey, and earth-brown unglazed clay only, no wood or metal",
    ),
    "이제 창업자의 수수께끼는 나라 이름의 수수께끼로 번집니다": (
        "02-084",
        "object-only transition from founder mystery to blank kingdom-name evidence",
        "Strict overhead on bare wood: one grey founder disk lies beside one long blank pale kingdom-name tile while a single shallow fracture extends from the disk toward the tile edge",
        "plain grey and pale unglazed clay on natural wood only",
    ),
}


BAEKJE_EP02_NAME_MIGRATION_LOCKS: dict[str, tuple[str, str, str, str]] = {
    "삼국사기에서는 많은 백성이 즐거이 따랐기에 백제라 했다고 전합니다": (
        "02-085",
        "object-only following-population explanation with many community pebbles converging on one kingdom disk",
        "Strict overhead in bright even daylight on uninterrupted medium blue-grey matte clay filling every edge: one dense irregular stream of at least twenty tiny earth-brown pebbles travels from the left edge toward one much larger smooth dark-red kingdom disk on the right, leaving one narrow clear gap before the disk; all objects are separate and blank",
        "plain earth-brown and dark-red unglazed clay on medium blue-grey matte clay only",
    ),
    "처음의 십제가 비류 집단을 받아들이며 백제로 커졌다는 흐름이죠": (
        "02-086",
        "object-only growth through integration using one red and one grey inset inside one larger kingdom tile",
        "Strict overhead in bright even daylight on uninterrupted pale bare wood filling every edge: one large intact smooth earth-brown square kingdom tile contains exactly two separate shallow blank insets side by side, one small red circle and one small grey oval; no other object, crack, or fragment is present",
        "plain red, grey, and earth-brown unglazed clay on pale natural wood only",
    ),
    "여기에는 갈라진 두 무리가 다시 합쳐지는 통합의 명분이 담겨 있습니다": (
        "02-087",
        "object-only reunion of two divided groups as exactly two fitted semicircular clay halves",
        "Strict overhead on uninterrupted pale clay: exactly one red semicircle and one grey semicircle fit along one straight seam to form one complete round disk",
        "plain red, grey, and pale unglazed clay only",
    ),
    "반면 중국 기록 계통에는 백가제해라는 전혀 다른 풀이가 남았고": (
        "02-088",
        "object-only alternate Chinese-record explanation with one sealed source bundle and one coastal-boat token",
        "Strict overhead on bare wood: one sealed blank bamboo-slip bundle lies far left and one small undecorated low wooden boat model lies far right across a broad empty gap",
        "bound bamboo slips, hemp cord, and plain aged wood only",
    ),
    "많은 집안, 곧 백가가 바다를 건넌 까닭에 백제라 불렀다고 하죠": (
        "02-089",
        "object-only many-household sea crossing represented by one small boat and five closed cargo bundles",
        "High oblique view on a blue-grey sea field: one low wooden coastal boat model carries exactly five separate closed woven household bundles and no occupants",
        "aged low-sided wood, woven hemp, and plain blue-grey clay only",
    ),
    "왕자 한 명의 이름보다 집단 전체의 이동을 앞세운 설명입니다": (
        "02-090",
        "object-only contrast between one individual marker and one much larger many-member migration cluster",
        "Strict overhead on pale bare wood: one tiny red individual disk sits far left while one broad brown migration tile carrying a clearly numerous field of at least ten small raised blank dots dominates the right side",
        "plain red and brown unglazed clay only",
    ),
    "배에 오른 건 군대만이 아니라 가족과 기술자, 생업 공동체였을 것이며": (
        "02-091",
        "object-only family and livelihood migration cargo in one unoccupied ancient coastal boat",
        "High oblique view in daylight: one low undecorated wooden coastal boat with no occupants carries a compact household cargo cluster of closed woven hemp bundles, exactly two plain unglazed earthenware storage jars, and several small plain stone loom weights; no metal tool, paddle, or loose implement is visible",
        "aged undecorated wood, woven hemp, early unglazed earthenware, and plain stone only",
    ),
    "전승은 그 거대한 이동의 기억을 네 글자로 눌러 담았습니다": (
        "02-092",
        "object-only compressed migration memory represented by exactly four blank square clay tiles",
        "Strict overhead in bright even daylight on uninterrupted pale bare wood filling every edge: exactly four identical small blank pale clay squares form one straight horizontal row with equal gaps and press across the center of one broad flat earth-brown oval migration slab; every surface is smooth and completely unmarked",
        "plain pale and earth-brown unglazed clay on pale natural wood only",
    ),
    "하지만 백가제해를 실제 승선 명단처럼 받아들이면 곤란합니다": (
        "02-093",
        "object-only rejection of a literal passenger list using one abstract empty canoe token and one sealed source bundle",
        "Strict overhead in bright even daylight on uninterrupted pale earth-brown clay filling every edge: one flat smooth dark-brown hollowed-log canoe-shaped clay token lies far left and one sealed blank bamboo-slip source bundle lies far right across a broad empty gap, with no individual markers between them; the canoe token has no planks, seats, ribs, or marks",
        "plain dark-brown unglazed clay, bound blank bamboo slips, and hemp cord only",
    ),
    "백이라는 숫자는 정확한 가구 수보다 많음을 나타내는 표현일 수 있고": (
        "02-094",
        "object-only indefinite multitude with a loose field of many separated pebbles beside one blank tally disk",
        "Strict overhead in bright even daylight on uninterrupted medium blue-grey matte clay filling every edge: one loose irregular field of at least twelve separated medium earth-tone pebbles occupies the left half while one large completely blank smooth grey tally disk occupies the right half; pebbles do not overlap and no numeral or mark appears",
        "medium natural earth-tone pebbles and plain grey unglazed clay on medium blue-grey matte clay only",
    ),
    "바다를 건넜다는 말도 구체적인 항로를 알려 주지는 않죠": (
        "02-095",
        "landscape-only unknown sea route with one small boat token and no path",
        "Top-down blue-grey sea relief filling every edge: exactly one tiny low wooden boat token floats near center amid uninterrupted water with no route line, coast label, or arrow",
        "plain blue-grey clay water and aged undecorated wood only",
    ),
    "황해를 가로질렀는지 연안을 따라 움직였는지 기록은 침묵합니다": (
        "02-096",
        "object-only unresolved open-sea versus coastal routes shown as exactly two unbroken clay ribbons on one abstract Yellow Sea tile",
        "Overhead on matte blue-grey clay sea with brown shore at right: exactly two separate unbroken ribbons stay far apart, one straight pale-tan ribbon across upper sea and one curved dark-brown ribbon along lower shore; no branch, crossing, touch, arrow, road, or bridge",
        "plain blue-grey, earth-brown, pale-tan, and dark-brown unglazed clay only",
    ),
    "따라서 이 문장은 증명서가 아니라 집단 이주의 기억에 가깝고": (
        "02-097",
        "object-only migration memory contrasted with documentary evidence using two smooth abstract clay forms",
        "Strict overhead in bright even daylight on uninterrupted medium blue-grey matte clay filling every edge: one large smooth earth-brown oval memory mass rests at left while one much smaller pale rectangular evidence block rests at right across a broad empty gap; both forms are blank, featureless, and unbroken",
        "plain earth-brown and pale unglazed clay on medium blue-grey matte clay only",
    ),
    "그 기억이 왜 중국 쪽 전승에서 살아남았는지가 더 중요한 질문입니다": (
        "02-098",
        "object-only survival of migration memory in one source marker across the sea",
        "Overhead on one continuous matte blue-grey clay sea between narrow brown shores at left and right: one small solid dark-brown oval migration pebble rests on the left shore and one small blank pale rectangular source block rests on the opposite right shore; no other object",
        "plain blue-grey, earth-brown, dark-brown, and pale unglazed clay only",
    ),
    "이름 하나가 온조의 통합 서사와 구태의 바다 서사를 동시에 품게 된 겁니다": (
        "02-099",
        "object-only one kingdom name carrying both integration and sea-migration memories",
        "Overhead on pale bare wood: one smooth blank red oval pebble and one smooth blank blue-grey canoe-shaped token rest separately on one long blank pale clay slab, with no writing, symbol, or mark anywhere",
        "plain red, blue-grey, and pale unglazed clay on pale natural wood only",
    ),
}


BAEKJE_EP02_MIXED_FOUNDING_LOCKS: dict[str, tuple[str, str, str, str]] = {
    "두 국호 풀이를 겹쳐 보면 승자가 패자를 지운 단순한 건국담은 무너집니다": (
        "02-100",
        "object-only overlap of two equal origin explanations around one kingdom marker",
        "Overhead on matte blue-grey clay: exactly two equal blank square tiles overlap by one third, pale-grey at left and brown at right, with both borders fully visible; one small smooth dark-red disk sits only on their shared overlap and neither tile is hidden",
        "plain pale-grey, earth-brown, and dark-red unglazed clay on medium blue-grey matte clay only",
    ),
    "한강 유역에는 이미 한계 토착 집단이 여러 정치체를 이루고 있었고": (
        "02-101",
        "object-only abstract Han River relief with exactly four separate native earthen polity enclosures",
        "Overhead on a handmade pale clay terrain tile: one winding blue-grey river channel crosses the tile; exactly four empty low oval rammed-earth bank rings occupy separate terraces, two on each side, with no fence, wall, house, field, bridge, or road",
        "plain river-silt clay, blue-grey clay water, and low undecorated rammed-earth banks only",
    ),
    "북쪽에서 내려온 부여계 세력도 한 번에 하나의 무리로만 오지 않았겠죠": (
        "02-102",
        "object-only multiple northern migration groups represented by exactly three separate group pebbles",
        "Overhead on pale earth-brown clay: exactly three identical smooth blank grey-brown oval pebbles occupy widely separated positions in one vertical line, one upper, one middle, and one lower; no other object",
        "plain grey-brown and pale earth-brown unglazed clay only",
    ),
    "여기에 예계 주민과 중국 군현에서 이동한 사람들까지 섞이며": (
        "02-103",
        "object-only material mixture of three communities using exactly three distinct archaeological fragments",
        "Overhead on pale clay: exactly three one-piece broken shards in one row: jagged red coarse pottery left, jagged grey burnished pottery center, and one wedge fragment of a circular aged-bronze mirror right showing part of its central knob and curved broken rim",
        "coarse reddish earthenware, grey burnished pottery, and dark aged bronze appropriate to early historic Korea only",
    ),
    "백제를 구성한 인구와 기술, 언어의 층은 점차 복잡해졌습니다": (
        "02-104",
        "object-only three-layer cultural mixture with one artifact embedded in each layer",
        "Bright high-oblique view on pale wood: one clay cutaway has exactly three horizontal layers, tan below, grey-brown middle, red above. One red pottery sherd protrudes from the lower layer, one dark iron fragment from the middle, and one pale oval pebble rests on top",
        "natural stratified clay, coarse pottery, bloomery-iron fragment, and plain fired clay only",
    ),
    "온조와 비류를 형제로 묶은 설화도 두 세력의 연합을 설명하는 장치로 읽히고": (
        "02-105",
        "object-only two-founder alliance represented by exactly two equal disks inside one shared boundary",
        "Strict overhead: exactly two equal red and grey founder disks rest side by side with a narrow gap inside one broad earth-brown square alliance field",
        "plain red, grey, and earth-brown unglazed clay only",
    ),
    "구태 계보는 그 연합 밖에 남은 또 다른 부여계 기억일 수 있습니다": (
        "02-106",
        "object-only outside lineage memory with two allied disks and one separate grey disk",
        "Strict overhead on bare wood: exactly two small red founder disks rest inside one square brown alliance tile while one separate grey lineage disk remains far outside across a clear gap",
        "plain red, brown, and grey unglazed clay only",
    ),
    "다만 이것 역시 기록을 해석한 가설이지 확인된 인물 명단은 아닙니다": (
        "02-107",
        "object-only unconfirmed hypothesis with three candidate tokens separated from one blank evidence block",
        "Overhead on pale bare wood: one pale square clay hypothesis slab holds exactly three identical small blank grey disks total in one straight row, while one blank pale rectangular evidence block sits far right across a broad gap and all remaining wood is empty",
        "plain pale and grey unglazed clay on natural bare wood only",
    ),
    "고고학이 보여 주는 무덤과 토기, 주거 흔적도 이동과 혼합을 말하지만": (
        "02-108",
        "object-only archaeological evidence with one tomb outline, one pottery cluster, and one posthole circle",
        "Top-down excavation surface: exactly three separated evidence zones show one low stone tomb outline, one cluster of plain pottery fragments, and one circular pattern of timber postholes",
        "natural soil, local stone, coarse earthenware, and decayed timber traces only",
    ),
    "특정 유물을 곧바로 온조나 구태의 소유물이라 부를 수는 없죠": (
        "02-109",
        "object-only unassignable artifact centered between two blank candidate markers",
        "Strict overhead on bare wood: one undecorated early Baekje pottery jar stands centered between exactly two equal blank grey candidate disks, with wide gaps and no ownership marks",
        "coarse early Baekje earthenware, grey unglazed clay, and natural wood only",
    ),
    "그래서 초기 백제는 한 영웅이 빈 땅에 세운 나라라기보다": (
        "02-110",
        "object-only rejection of a lone-founder model using four community markers and an empty center",
        "Strict overhead on one broad earth-brown field: exactly four differently colored community disks occupy the four corners around a completely empty center, with no single dominant marker",
        "plain earth-brown, red, grey, ochre, and dark-brown unglazed clay only",
    ),
    "여러 집단이 경쟁하고 합치며 권력의 중심을 만든 과정으로 보입니다": (
        "02-111",
        "object-only consolidation process with four group disks forming one power center",
        "Strict overhead: exactly four small colored group disks touch four different sides of one larger central dark-red power disk on uninterrupted pale clay",
        "plain red, grey, ochre, brown, and pale unglazed clay only",
    ),
    "이 과정에서는 동맹이 깨지고 우두머리가 바뀌는 충돌도 있었을 것이나": (
        "02-112",
        "object-only possible political conflict with one broken alliance boundary and one displaced center marker",
        "Strict overhead on bare wood: one cracked brown alliance ring lies open while one red leadership disk rests outside its former central impression across a short empty gap",
        "plain brown and red unglazed clay on natural wood only",
    ),
    "기록이 남기지 않은 전투와 배신을 구체적으로 꾸며낼 수는 없습니다": (
        "02-113",
        "object-only absence of evidence for undocumented battle or betrayal",
        "Overhead on medium blue-grey matte clay: exactly two single one-piece pale angular boundary sherds lie flat and isolated, one far left and one far right, with each side holding one sherd only and broad empty center between them",
        "plain medium blue-grey and pale unglazed clay only",
    ),
    "대신 서로 다른 시조 이름이 그 격렬한 통합의 흔적을 대신 말해 주죠": (
        "02-114",
        "object-only three competing founder memories fused into one exactly three-piece composite kingdom tile",
        "Overhead on pale wood: one long composite kingdom tile consists of exactly three equal rectangular clay segments joined edge-to-edge in a straight row, red at left, grey at center, brown at right, with no other segment or object",
        "plain red, grey, and brown unglazed clay on natural bare wood only",
    ),
}


BAEKJE_EP02_RIVER_SEA_LOCKS: dict[str, tuple[str, str, str, str]] = {
    "그렇다면 해양 제국의 씨앗은 정확히 어디에 있었을까요": (
        "02-115",
        "landscape-only Han River estuary seed at the river-sea junction",
        "Top-down natural relief of the Han River meeting Yellow Sea tidal flats: exactly one tiny dark-red clay seed marker rests at the junction of brown river silt and blue-grey water",
        "natural river silt, tidal mudflat clay, blue-grey water clay, and one red marker only",
    ),
    "답은 거대한 함대보다 한강과 서해가 만나는 지형에서 먼저 보입니다": (
        "02-116",
        "landscape-only Han River mouth and Yellow Sea mudflats without any fleet",
        "High aerial view of one broad natural river channel opening into wide tidal flats and low rocky islands; empty water reaches the horizon with no boat, ship, craft, wake, harbor, road, field, building, or other constructed feature at any distance",
        "natural water, tidal mudflats, reed banks, and low rocky islands only",
    ),
    "한강은 내륙의 곡물과 철, 사람을 서해안으로 실어 나를 수 있었고": (
        "02-117",
        "object-only river transport boat with three inland cargo types and no occupants",
        "Bright high-oblique view over pale sunlit water: one fully visible low-sided wooden river craft carries exactly three objects, one opaque reddish-brown unglazed grain jar sealed with a clay stopper, one rough iron bloom, and one closed woven hemp travel bundle",
        "pale natural shallow water, aged unpainted wood, coarse earthenware, bloomery iron, and woven hemp only",
    ),
    "서해 연안은 조수와 섬을 이용해 북쪽과 남쪽을 잇는 통로가 됐습니다": (
        "02-118",
        "landscape-only west-coast tidal corridor formed by exactly four low island insets",
        "Overhead on pale wood: one long plain blue-grey clay water slab holds exactly four brown oval island tokens in four fixed slots across one straight row, far-left, center-left, center-right, and far-right, with one token in each slot and all remaining blue clay empty",
        "plain blue-grey and brown unglazed clay on natural bare wood only",
    ),
    "강을 장악한 세력은 내륙 생산지와 바닷길을 함께 붙잡을 수 있었죠": (
        "02-119",
        "landscape-only river-mouth control connecting inland production and sea passage",
        "Overhead on pale bare wood: one flat handmade estuary tile has one brown clay upstream strip meeting one blue-grey coastal strip, with exactly one small dark-red square control block at their junction and no other object",
        "plain dark-red, brown, and blue-grey unglazed clay on natural bare wood only",
    ),
    "하지만 건국 직후부터 원양 함대가 바다를 지배했다는 증거는 없습니다": (
        "02-120",
        "object-only absence of an early ocean fleet with one small river craft beside empty open sea",
        "High oblique view: exactly one tiny low-sided wooden river craft rests near a muddy shore while the entire blue-grey open-sea field beyond remains empty without other vessels",
        "aged low-sided wood, natural mudflat silt, and blue-grey water only",
    ),
    "초기 이동에는 연안용 작은 배와 강을 오가는 선박이 더 어울립니다": (
        "02-121",
        "object-only two modest early watercraft suited to river and coast",
        "High oblique view on blue-grey clay water: exactly two empty low-sided wooden craft appear, one narrow river craft near reeds and one slightly broader coastal craft near a muddy shore, both without high decks",
        "simple aged wood, reed bank, mudflat silt, and blue-grey water only",
    ),
    "사람들은 물길을 따라 소금과 곡물, 금속과 정보를 옮겼고": (
        "02-122",
        "object-only waterborne exchange cargo with exactly four goods in one empty boat",
        "Bright high-oblique view over pale clay water: one low wooden boat carries exactly four objects total, one closed woven salt basket, one sealed earthenware grain jar, one rough black iron bloom, and one short closed blank bamboo-slip bundle tied with hemp cord",
        "aged wood, woven reed, coarse earthenware, bloomery iron, bamboo slips, and hemp cord only",
    ),
    "그 반복된 왕래가 먼 지역과 거래하는 기술을 쌓게 했습니다": (
        "02-123",
        "object-only repeated coastal voyages shown by three boat tokens at successive positions",
        "Strict overhead on one long blue-grey coastal band: exactly three identical small wooden boat tokens occupy three separated successive positions from left to right with no arrows or route labels",
        "plain blue-grey clay water and aged undecorated wood only",
    ),
    "항구는 물건만 모이는 곳이 아니라 낯선 소문과 외교 정보가 모이는 곳이었죠": (
        "02-124",
        "object-only early harbor exchange with goods and one sealed diplomatic information pouch",
        "Bright overhead on pale rough timber: exactly three objects total rest apart, one matte coarse red unglazed jar, one closed lidded woven salt basket, and one small plain tan hemp information pouch tied completely shut with one cord, with no document or writing",
        "rough early timber, coarse earthenware, woven reed, plain tan hemp cloth, and hemp cord only",
    ),
    "어느 세력이 강 어귀를 차지하느냐에 따라 주변 연맹의 힘도 달라졌고": (
        "02-125",
        "landscape-only estuary control affecting three surrounding alliance markers",
        "Overhead on pale wood: one square pale bank tile fills center, exactly three brown circular insets form one straight row across its upper half, and one narrow blue-grey channel ends at one red square centered below the row; no other disk or marker",
        "plain blue-grey, brown, and red unglazed clay on natural bare wood only",
    ),
    "백제는 바로 그 교차점에서 성장할 수 있는 조건을 얻었습니다": (
        "02-126",
        "landscape-only Baekje growth marker at the Han River and Yellow Sea intersection",
        "Overhead on pale wood: one square clay relief fills center, one brown river strip enters from top and meets one broad blue-grey sea strip along the bottom, and exactly one dark-red disk sits centered on their junction, while all remaining clay is plain",
        "plain brown, blue-grey, and dark-red unglazed clay on natural bare wood only",
    ),
    "구태 설화의 바다는 완성된 제국의 증거가 아니라": (
        "02-127",
        "object-only small sea-legend token contrasted with an empty imperial-scale field",
        "Strict overhead: one tiny wooden boat-shaped legend token rests at the far edge of one vast uninterrupted blue-grey sea tile whose entire center remains empty without fleet or royal emblem",
        "aged undecorated wood and plain blue-grey unglazed clay only",
    ),
    "이동과 교류를 나라의 기원으로 기억한 상징에 더 가깝습니다": (
        "02-128",
        "object-only origin symbol of movement and exchange between two shores",
        "Strict overhead on blue-grey clay water: exactly one small wooden boat token carrying one closed woven bundle sits midway between exactly two separate brown shoreline blocks",
        "aged wood, woven hemp, plain blue-grey water clay, and brown shore clay only",
    ),
    "이 작은 씨앗이 실제 해상 외교망이 되기까지는 긴 시간이 필요했죠": (
        "02-129",
        "object-only long development from one small marker to one later tile containing exactly three parallel sea channels",
        "Overhead on one long blank brown clay strip: one tiny plain red round disk rests at far left while one small blue-grey square channel tile at far right holds exactly three straight parallel shallow grooves only, across a broad undecorated empty middle",
        "plain earth-brown, red, and blue-grey unglazed clay only",
    ),
}


BAEKJE_EP02_MARITIME_POWER_LOCKS: dict[str, tuple[str, str, str, str]] = {
    "수 세기가 흐른 뒤 백제는 그 지리적 이점을 현실의 힘으로 바꿉니다": (
        "02-130",
        "object-only centuries-long growth from one small estuary marker to one large later kingdom disk",
        "Strict overhead on one long blank chronology strip: one tiny red estuary marker rests at far left while one much larger dark-red kingdom disk rests at far right across a broad empty span",
        "plain earth-brown, red, and dark-red unglazed clay only",
    ),
    "낙랑과 대방이 무너진 뒤 황해의 기존 교통망에는 빈틈이 생겼고": (
        "02-131",
        "object-only collapse of two commandery nodes opening one Yellow Sea corridor gap",
        "Strict overhead on blue-grey clay water: exactly two cracked grey commandery tiles lie far apart at left and right, leaving one broad empty central sea corridor between their broken inner edges",
        "plain blue-grey and weathered grey unglazed clay only",
    ),
    "백제는 중국 대륙과 한반도 남부, 일본열도를 잇는 길에 뛰어듭니다": (
        "02-132",
        "landscape-only Baekje entry into three East Asian sea-route directions",
        "Overhead on pale wood: one triangular blue-grey clay sea tile holds one small red disk at its center and exactly three brown shore blocks at its three corners, with exactly three short shallow grooves linking the center disk once to each block and no other object",
        "plain blue-grey, earth-brown, and dark-red unglazed clay on natural bare wood only",
    ),
    "특히 근초고왕 시대에는 정복과 외교, 교역이 함께 움직였고": (
        "02-133",
        "object-only Geunchogo-era conquest diplomacy and trade shown by three period objects",
        "Bright overhead on pale clay: exactly three objects rest apart, one narrow leaf-shaped weathered iron spearhead, one short tied blank bamboo-slip bundle, and one coarse unglazed trade jar",
        "pale matte clay, fourth-century bloomery iron, bound bamboo slips, hemp cord, and Baekje earthenware only",
    ),
    "동진과 사신을 주고받으며 국제질서 안에서 왕의 위상을 세웠습니다": (
        "02-134",
        "object-only fourth-century diplomatic exchange between Baekje and Eastern Jin",
        "Strict overhead on blue-grey clay water: exactly two sealed blank diplomatic bundles face each other on opposite shores with one small low wooden sea-boat token centered between them",
        "bound bamboo slips, aged silk wrapping, hemp cord, aged wood, and plain clay shores only",
    ),
    "가야와 왜로 이어지는 남쪽 항로도 백제의 전략 자산이 됐으며": (
        "02-135",
        "landscape-only southern maritime routes from Baekje toward Gaya and Wa",
        "Overhead on pale bare wood: one blue-grey clay sea tile holds one red square port marker at upper-left, one brown shore block at lower-left, and one brown island block at lower-right, with exactly two shallow grooves linking the red marker separately to each block",
        "plain blue-grey, earth-brown, and red unglazed clay on natural bare wood only",
    ),
    "칠지도 같은 유물은 그 복잡한 관계가 물질로 남은 사례죠": (
        "02-136",
        "object-only exact archaeological Seven-Branched Sword from Isonokami Shrine: one central iron blade, three side branches on each edge, six alternating branches total, narrow blunt tang",
        "Overhead artifact view of the actual Seven-Branched Sword, Shichishito, from Isonokami Shrine: one long central iron body with three branch blades sprouting from each side at alternating heights. Exactly seven blade tips total: one central tip plus six side tips",
        "weathered fourth-century iron and plain pale beige woven hemp only",
    ),
    "학자와 기술, 불교와 문자 문화도 배를 타고 오가게 됩니다": (
        "02-137",
        "object-only one flat boat-shaped clay cargo tray carrying a closed bamboo-slip bundle, one uniform bronze craft strip, and one shallow lotus dish",
        "Overhead on pale blue-grey clay: one flat brown clay boat-shaped tray holds exactly three separate objects: one tied closed tan bamboo-slip bundle, one short uniform-width rectangular bronze craft strip, and one shallow round bronze lotus dish. Every surface is blank",
        "plain blue-grey and brown clay, bound bamboo slips, hemp cord, and simple Baekje-period bronze only",
    ),
    "이때의 백제라면 해양 강국이라는 표현이 비로소 역사와 맞닿지만": (
        "02-138",
        "object-only mature Baekje maritime capacity represented by exactly three simple wooden vessel tokens",
        "Overhead on one plain blue-grey clay sea tile: exactly three separate flat wooden low-boat tokens form a wide row, each token has one short hull and one single small rectangular woven sail on one short mast, with no high deck, cabin, figure, or other vessel",
        "plain blue-grey unglazed clay, aged undecorated wood, and simple woven cloth only",
    ),
    "그 힘을 구태의 시대부터 완성돼 있었다고 거꾸로 밀어 넣어선 안 됩니다": (
        "02-139",
        "object-only two separated unmarked clay crescent boat counters of different sizes",
        "Overhead on a full-frame bright pale-clay field: exactly two flat solid dark-brown clay boat-shaped counters appear, one tiny at far left and one larger at far right across a broad empty center; each is a simple filled crescent hull with a smooth featureless interior",
        "plain pale clay and two undecorated dark-brown clay boat counters only",
    ),
    "설화가 씨앗이라면 제국의 모습은 수백 년 동안 쌓인 결과였고": (
        "02-140",
        "object-only one round legend marker and one later three-channel maritime tile separated by centuries",
        "Overhead on pale wood: one long blank brown chronology strip holds one small round grey legend disk at far left and one pale square route tile at far right containing exactly three narrow blue-grey straight bars in one parallel row, while the broad middle remains empty",
        "plain grey, earth-brown, and blue-grey unglazed clay only",
    ),
    "건국의 바다와 전성기의 바다는 같은 물길 위에서도 다른 시대였죠": (
        "02-141",
        "object-only one tiny and three larger unmarked crescent boat counters on the same sea field",
        "Overhead on one full-frame blue-grey sea tile: exactly four flat solid brown crescent boat counters appear, one tiny crescent alone at far left and exactly three equal larger crescents form one vertical column at far right, one top, one middle, and one bottom, across a broad empty center",
        "plain blue-grey unglazed clay and four flat brown clay boat counters only",
    ),
    "그 차이를 구분해야 구태 이야기도 과장 없이 더 흥미로워집니다": (
        "02-142",
        "object-only honest separation of early and later maritime evidence",
        "Overhead on pale wood: one tiny plain flat wooden boat silhouette rests on a pale square pad at left, and one larger plain flat wooden boat silhouette rests on a dark-grey square pad at right; both are bare hull outlines without mast, sail, cabin, roof, rail, or cross",
        "aged wood and plain pale and dark-grey unglazed clay only",
    ),
    "온조를 지우지 않아도 구태의 수수께끼는 살아남고": (
        "02-143",
        "object-only coexistence of one established founder marker and one unresolved mystery marker",
        "Strict overhead: one solid red founder disk and one weathered grey mystery disk remain fully visible with a clear gap on the same broad earth-brown kingdom tile",
        "plain red, weathered grey, and earth-brown unglazed clay only",
    ),
    "구태를 왕으로 확정하지 않아도 복합적인 백제의 출발은 보입니다": (
        "02-144",
        "object-only composite Baekje beginning without a crowned central founder",
        "Overhead on pale clay: exactly four small smooth blank irregular clay pebbles, red, grey, ochre, and dark-brown, occupy four corners around one large smooth blank earth-brown kingdom disk, while every surface remains featureless with no rim or mark",
        "plain pale, earth-brown, red, grey, ochre, and dark-brown unglazed clay only",
    ),
}


BAEKJE_EP02_SYNTHESIS_TEASER_LOCKS: dict[str, tuple[str, str, str, str]] = {
    "결국 백제의 출생증명서는 한 장이 아니라 여러 장이었습니다": (
        "02-145",
        "object-only exactly four objects: three unmarked source bundles above exactly one plain kingdom disk; one disk total; no fifth object",
        "Overhead on pale wood: exactly four objects only. Top: one tied bamboo-slip bundle, one beige silk packet, one undivided brown hemp packet. Bottom: exactly one dark-red clay disk. One disk total in frame; empty wood surrounds all four blank objects",
        "bound bamboo slips, aged silk, woven hemp, cord, and plain dark-red clay only",
    ),
    "삼국사기는 온조와 비류의 남하를 왕실 정통성의 중심에 놓았고": (
        "02-146",
        "object-only Onjo and Biryu southward-descent tradition with two equal founder markers",
        "Strict overhead on pale clay: only two identical flat red disks travel side by side halfway down one straight north-to-south earth path ending at one narrow blue-grey river band along the bottom edge",
        "plain red, earth-brown, and blue-grey unglazed clay only",
    ),
    "중국 기록은 구태와 대방, 공손씨의 혼인동맹을 기억했습니다": (
        "02-147",
        "object-only unmarked three-piece clay chain representing Guthe, Daifang, and Gongsun alliance",
        "Strict overhead on bare pale clay: exactly three clay pieces total touch edge-to-edge in one horizontal chain, one flat grey circle at left, one flat blue-grey rectangle at center, and one flat reddish circle at right",
        "plain grey, blue-grey, and reddish unglazed clay only",
    ),
    "국호도 백성이 즐겨 따랐다는 설명과 백가가 바다를 건넜다는 설명으로 갈렸죠": (
        "02-148",
        "object-only two origin explanations: one irregular one-piece red community cluster and one boat-shaped tray holding exactly three migration packets",
        "Overhead on pale wood: far left lies one irregular one-piece red clay community token made of many fused round lobes, never a smooth disk. Far right lies one brown boat-shaped tray holding exactly three separate tan packets. Wide empty wood separates them",
        "plain red clay, aged wood, woven hemp, and natural bare wood only",
    ),
    "서로 맞지 않는 기록은 혼란이 아니라 초기 백제의 복잡성을 드러냅니다": (
        "02-149",
        "object-only complexity revealed by four different blank source tokens around one kingdom marker",
        "Strict overhead on pale clay: one blank circle at top, one blank square at right, one blank oval at bottom, and one blank triangle at left each directly touch a different edge of one central dark-red disk; exactly five objects total",
        "plain pale, grey, brown, ochre, and dark-red unglazed clay only",
    ),
    "여러 집단의 기억이 한 왕조 안에서 경쟁하다 함께 남았고": (
        "02-150",
        "object-only competing group memories preserved around one kingdom disk",
        "Strict overhead on bare wood: one small blank red disk at left, one small blank grey disk at right, and one small blank ochre disk at bottom each directly touch a different edge of one large blank earth-brown central disk; exactly four disks total",
        "plain red, grey, ochre, and earth-brown unglazed clay only",
    ),
    "후대의 편찬자들조차 어느 하나를 완전히 지우지 못했습니다": (
        "02-151",
        "object-only three intact source traditions preserved without erasure",
        "Strict overhead on uninterrupted bare wood: only three sealed blank source bundles lie side by side, one short rectangular tied bundle of parallel bamboo slips at left, one folded tan silk packet at center, and one rectangular tied brown hemp packet at right",
        "bound bamboo slips, aged silk, woven hemp, and natural wood only",
    ),
    "그래서 구태는 가짜 창업자도 확정된 초대왕도 아닌": (
        "02-152",
        "object-only unresolved founder status between rejection and an empty royal seat",
        "Strict overhead on bare wood: one weathered grey mystery disk sits centered between one cracked pale rejection tile at left and one empty dark-red round royal-seat impression at right",
        "plain weathered grey, pale, and dark-red unglazed clay only",
    ),
    "백제가 하나의 혈통만으로 태어나지 않았음을 묻는 이름으로 남습니다": (
        "02-153",
        "object-only multiple lineages converging into one composite Baekje kingdom",
        "Strict overhead on pale clay: one large smooth blank circular earth-brown disk sits centered; exactly three small solid triangular wedges, red at left, grey at top, and ochre at right, each touch the disk with one tip",
        "plain red, grey, ochre, earth-brown, and pale unglazed clay only",
    ),
    "그리고 다음 단계에서는 설화가 아니라 제도와 권력이 움직이기 시작하죠": (
        "02-154",
        "object-only transition from legend to institutions and centralized power",
        "Strict overhead on a full-frame bright pale-tan clay field: only one smooth blank faded-grey disk rests at far left and one smooth blank dark-red square block rests at far right across a broad empty center; exactly two objects total",
        "plain earth-brown, faded grey, and dark-red unglazed clay only",
    ),
    "다음 편은 백제를 연맹의 한 나라에서 중앙집권 국가로 끌어올린 고이왕입니다": (
        "02-155",
        "object-only King Goi centralization teaser with one royal disk above exactly four grey rank blocks in a two-by-two square",
        "Overhead on a pale field: one blank dark-red disk sits at top. Below it exactly four equal grey square blocks form a clean two-by-two grid: two top and two bottom, all separate. Exactly five objects total",
        "plain pale, dark-red, and grey unglazed clay only",
    ),
    "낙랑과 대방의 전쟁으로 마한의 질서가 흔들리는 바로 그 틈에서": (
        "02-156",
        "object-only exactly six objects: two cracked commandery-war tiles above exactly four smaller Mahan polity blocks",
        "Overhead on earth-brown clay: exactly six objects total. At top, exactly two cracked grey tiles, one far left and one far right. At bottom, exactly four smaller brown blocks form a two-by-two grid: upper-left, upper-right, lower-left, lower-right. Center stays empty",
        "plain weathered grey and earth-brown unglazed clay only",
    ),
    "고이왕은 주변 세력을 누르고 관등과 법, 군사 지휘권을 손에 쥡니다": (
        "02-157",
        "object-only third-century royal control: one plain matte royal disk, four rank blocks, one law tablet, and one military spearhead",
        "Overhead on pale clay: exactly seven objects. Top: one flat matte dark-red unglazed clay disk with a smooth blank face, no rim or relief. Bottom: four grey rank blocks in a two-by-two grid at left, one blank tan law tablet at center, one narrow iron spearhead at right",
        "third-century plain fired clay, bloomery iron, and dark-red unglazed clay only",
    ),
    "왕의 옷 색깔까지 권력의 서열이 되는 순간을 다음 편에서 이어가겠습니다": (
        "02-158",
        "object-only recorded Baekje rank-cloth color hierarchy teaser",
        "Strict overhead on bare wood: exactly three folded blank rank-cloth swatches lie in descending order, one deep purple, one red, and one blue, with clear equal gaps and no bodies",
        "plain woven hemp and silk cloth dyed deep purple, red, and blue only",
    ),
    "백제의 다음 권력투쟁이 궁금하시다면 구독과 좋아요로 함께해 주세요": (
        "02-159",
        "object-only next-episode power-struggle hook with two rival authority markers",
        "Strict overhead on one cracked earth-brown authority tile: one dark-red royal disk faces one grey rival disk across one broad central fracture, with both blank and fully visible",
        "plain earth-brown, dark-red, and grey unglazed clay only",
    ),
}


BAEKJE_EP02_REMAINING_LOCKS: dict[str, tuple[str, str, str, str]] = {
    **BAEKJE_EP02_RITUAL_MEMORY_LOCKS,
    **BAEKJE_EP02_NAME_MIGRATION_LOCKS,
    **BAEKJE_EP02_MIXED_FOUNDING_LOCKS,
    **BAEKJE_EP02_RIVER_SEA_LOCKS,
    **BAEKJE_EP02_MARITIME_POWER_LOCKS,
    **BAEKJE_EP02_SYNTHESIS_TEASER_LOCKS,
}


BAEKJE_EP02_REMAINING_EXTRA_NEGATIVE_TERMS_BY_ROW: dict[str, tuple[str, ...]] = {
    "02-070": (
        "coin",
        "seal",
        "medallion",
        "ring",
        "groove",
        "carved symbol",
        "engraved mark",
        "source bundle",
        "book",
        "page",
        "paper",
        "cloth",
        "bamboo slip",
    ),
    "02-071": (
        "pagoda",
        "stone temple",
        "tile roof",
        "thatched roof",
        "standing roof",
        "ornate eaves",
        "modern shrine",
    ),
    "02-072": (
        "fifth marker",
        "third marker",
        "two ritual markers",
        "three ritual markers",
        "six ritual markers",
        "empty grid cell",
        "single row",
        "round ritual marker",
        "bowl",
        "cup",
        "plate",
        "large plate",
        "circular face layout",
        "ring",
        "coin",
        "seal",
        "food",
        "flame",
        "black background",
        "dark surface",
    ),
    "02-073": (
        "coin",
        "seal",
        "medallion",
        "round grey token",
        "carved symbol",
        "engraved mark",
        "letter",
        "glyph",
        "black border",
        "dark frame",
        "vignette",
    ),
    "02-074": ("fourth descendant disk", "second ancestor disk"),
    "02-075": (
        "fourth marker",
        "third grey alternative",
        "second grey triangle",
        "second grey square",
        "corner markers",
        "marker on slab corner",
        "coin",
        "seal",
        "glyph",
        "engraving",
    ),
    "02-078": (
        "third marker",
        "coin",
        "seal",
        "medallion",
        "emblem",
        "crossed tools",
        "carved symbol",
        "engraved mark",
        "letter",
        "glyph",
        "inscription",
        "black background",
        "dark border",
        "dark frame",
        "vignette",
    ),
    "02-079": (
        "third ritual field",
        "third ancestor marker",
        "carved symbol",
        "engraved mark",
        "letter",
        "glyph",
        "inscription",
        "seal",
        "coin",
        "small pebble",
        "small marker",
        "third object",
        "black background",
        "dark border",
        "dark frame",
        "vignette",
    ),
    "02-080": (
        "fourth lineage marker",
        "fifth lineage marker",
        "second grey marker",
        "second brown marker",
        "second red marker",
        "circular arrangement",
        "triangle",
        "square marker",
        "rough surface",
        "crack",
        "pit",
        "carved symbol",
        "letter",
        "glyph",
        "black background",
        "dark border",
        "dark frame",
        "vignette",
    ),
    "02-082": (
        "fourth founder token",
        "repeated shape",
        "second red circle",
        "second grey oval",
        "second brown square",
        "base slab",
        "black background",
        "dark border",
        "dark frame",
        "vignette",
        "carved symbol",
        "letter",
        "glyph",
    ),
    "02-083": (
        "vertical slab",
        "standing rectangle",
        "book",
        "phone",
        "smartphone",
        "tablet computer",
        "electronic device",
        "port",
        "button",
        "screen",
        "letter",
        "number",
        "glyph",
        "inscription",
        "third grey pebble",
    ),
    "02-085": (
        "three community markers",
        "five community markers",
        "single community marker",
        "neat small group",
        "closed ring",
        "circle of pebbles",
        "halo",
        "pebbles surrounding disk",
        "white background",
        "white border",
        "white frame",
        "pale wood",
        "human",
        "crowd of people",
    ),
    "02-086": (
        "third inset",
        "second red inset",
        "second grey inset",
        "loose object",
        "broken tile",
        "crack",
        "fragment",
        "shard",
        "speech bubble",
        "handle",
    ),
    "02-089": ("sixth bundle", "fourth bundle", "sail", "warship"),
    "02-090": (
        "exactly five dots",
        "small dot cluster",
        "second individual disk",
        "human",
        "person",
    ),
    "02-091": (
        "metal tool",
        "bronze tool",
        "iron tool",
        "wrench",
        "drill",
        "saw",
        "clamp",
        "tongs",
        "modern implement",
        "paddle",
        "oar",
        "weapon pile",
        "warrior",
        "occupant",
    ),
    "02-092": (
        "fifth square",
        "third square",
        "two squares",
        "woven bundle",
        "rope",
        "cord coil",
        "seal",
        "stamp",
        "letter",
        "number",
        "glyph",
        "inscription",
        "carved mark",
    ),
    "02-093": (
        "plank boat",
        "rowboat",
        "bench",
        "seat",
        "rib",
        "keel",
        "raised prow",
        "metal nail",
        "letter",
        "number",
        "glyph",
        "inscription",
        "passenger marker",
        "human",
        "person",
    ),
    "02-094": (
        "dense mound",
        "overlapping pebbles",
        "tiny grain",
        "mosaic",
        "pattern",
        "letter",
        "number",
        "numeral",
        "glyph",
        "inscription",
        "white background",
        "white border",
        "white frame",
    ),
    "02-096": (
        "third ribbon",
        "third route",
        "hemp cord",
        "rope",
        "branching line",
        "forked line",
        "crossing lines",
        "route arrow",
        "map label",
        "road",
        "highway",
        "causeway",
        "bridge",
        "breakwater",
        "railway",
        "vehicle",
        "modern coast",
        "coastal development",
        "photorealistic aerial landscape",
        "text",
        "letter",
        "number",
        "glyph",
    ),
    "02-097": (
        "woven bundle",
        "rope coil",
        "cord ball",
        "bamboo slips",
        "book",
        "paper",
        "letter",
        "number",
        "glyph",
        "inscription",
        "black background",
        "dark border",
        "dark frame",
        "vignette",
    ),
    "02-098": (
        "square sea tile",
        "multiple blue tiles",
        "tile seam",
        "grout",
        "swimming pool",
        "same shore",
        "central bundle",
        "plank rowboat",
        "canoe",
        "boat",
        "hollow token",
        "crossbar",
        "seat",
        "human",
        "person",
        "body",
        "letter",
        "number",
        "glyph",
        "inscription",
        "black background",
        "dark frame",
        "vignette",
    ),
    "02-099": (
        "coin",
        "seal",
        "medallion",
        "emblem",
        "carved symbol",
        "engraved mark",
        "letter",
        "number",
        "glyph",
        "inscription",
        "writing",
        "black background",
        "dark border",
        "dark frame",
        "vignette",
    ),
    "02-100": (
        "single source tile",
        "third source tile",
        "fully hidden tile",
        "stacked identical tiles",
        "second kingdom disk",
        "letter",
        "number",
        "glyph",
        "inscription",
        "black background",
        "dark frame",
    ),
    "02-101": (
        "fifth enclosure",
        "third enclosure",
        "fence",
        "wooden fence",
        "stone castle",
        "palace",
        "tiled roof",
        "modern house",
        "farm field",
        "field grid",
        "bridge",
        "road",
        "highway",
        "utility pole",
        "power line",
        "modern embankment",
        "photorealistic aerial landscape",
        "vehicle",
    ),
    "02-102": (
        "fourth group pebble",
        "second upper pebble",
        "second middle pebble",
        "second lower pebble",
        "bundle",
        "rope",
        "jar",
        "wagon",
        "horse",
        "human",
        "black background",
        "dark border",
        "vignette",
    ),
    "02-103": (
        "fourth artifact",
        "complete jar",
        "complete grey disk",
        "complete grey plate",
        "round red disk",
        "round grey disk",
        "grey bowl",
        "complete mirror",
        "stacked fragments",
        "bottle",
        "vessel handle",
        "plate",
        "modern pottery",
        "polished new bronze",
        "hexagonal mirror",
        "octagonal mirror",
        "polygon mirror",
        "perfect geometric mirror",
        "letter",
        "number",
        "glyph",
        "inscription",
        "watermark",
        "logo",
        "signature",
        "caption",
        "black background",
        "dark frame",
    ),
    "02-104": (
        "fourth layer",
        "fourth artifact",
        "modern tool",
        "spoon",
        "key",
        "knife",
        "handle",
        "branching groove",
        "carved symbol",
        "letter",
        "number",
        "glyph",
        "inscription",
        "black background",
        "dark frame",
        "vignette",
        "missing lower pottery sherd",
        "identical layer colors",
    ),
    "02-107": (
        "book",
        "paper",
        "page",
        "bound volume",
        "bamboo slips",
        "bundle",
        "rope",
        "document",
        "fourth candidate disk",
        "fifth candidate disk",
        "only two candidate disks",
        "only one candidate disk",
        "second evidence block",
        "connecting line",
        "arrow",
        "letter",
        "glyph",
        "inscription",
    ),
    "02-108": ("fourth evidence zone", "complete modern house", "modern excavation equipment"),
    "02-110": ("fifth community disk", "central hero disk"),
    "02-111": ("fifth group disk", "sixth group disk"),
    "02-113": (
        "third boundary fragment",
        "fourth boundary fragment",
        "four corner fragments",
        "stacked sherds",
        "overlapping sherds",
        "paired fragments",
        "two pieces at left",
        "two pieces at right",
        "black slab",
        "weapon",
        "human body",
    ),
    "02-114": (
        "fourth founder disk",
        "fourth marker",
        "fifth founder disk",
        "fourth segment",
        "fifth segment",
        "sixth segment",
        "wedge segment",
        "circular disk",
        "pie chart",
        "second red marker",
        "second grey marker",
        "third grey marker",
        "extra grey marker",
        "symmetric grey pair",
        "second brown marker",
        "map outline",
        "coastline",
        "engraved boundary",
        "crack",
        "glyph",
        "inscription",
    ),
    "02-116": (
        "boat",
        "ship",
        "watercraft",
        "motorboat",
        "speedboat",
        "wake",
        "harbor",
        "dock",
        "building",
        "paved road",
        "cultivated field",
        "farm grid",
        "bridge",
        "vehicle",
        "power line",
    ),
    "02-117": (
        "fourth cargo object",
        "second boat",
        "ocean ship",
        "motor",
        "engine",
        "propeller",
        "metal hull",
        "fiberglass hull",
        "painted hull",
        "transparent jar",
        "glass jar",
        "glass",
        "screw-top jar",
        "screw thread",
        "metal lid",
        "open jar",
        "visible grain",
        "plastic",
        "black background",
        "dark water",
        "dark frame",
        "vignette",
        "night",
        "dense foliage",
        "tree canopy",
    ),
    "02-118": (
        "fifth island",
        "only two islands",
        "two island insets",
        "third island only",
        "only three islands",
        "three island insets",
        "second channel",
        "third channel",
        "bridge",
        "boat",
        "ship",
        "sail",
        "mast",
        "buoy",
        "pole",
        "lighthouse",
        "building",
        "pier",
        "photoreal aerial landscape",
    ),
    "02-119": (
        "second control block",
        "road",
        "farmland",
        "cultivated field",
        "vehicle track",
        "tire track",
        "building",
        "bridge",
        "dam",
        "sluice",
        "gate",
        "photoreal aerial landscape",
    ),
    "02-121": ("third craft", "high deck", "ocean fleet", "dragon head"),
    "02-122": (
        "fifth cargo object",
        "second boat",
        "open document",
        "open basket",
        "spilled salt",
        "second salt container",
        "second basket",
        "paper",
        "page",
        "book",
        "white document",
        "label",
        "text",
        "glass jar",
        "transparent jar",
        "modern jar",
    ),
    "02-123": ("fourth boat token", "route arrow", "wake arrow"),
    "02-124": (
        "fourth harbor object",
        "modern dock",
        "crane",
        "paper parcel",
        "paper page",
        "white paper",
        "rolled paper",
        "paper scroll",
        "rolled sheet",
        "label",
        "text",
        "writing",
        "glyph",
        "cardboard box",
        "plastic package",
        "modern package",
        "open bundle",
        "glass jar",
        "glossy glazed jar",
        "open jar",
        "uncovered bamboo slips",
        "bamboo slips",
        "bamboo bundle",
        "wooden slats",
        "cut slat ends",
        "open pouch",
        "second pouch",
    ),
    "02-125": (
        "fourth alliance disk",
        "fifth alliance disk",
        "second control marker",
        "six disks",
        "only two brown disks",
        "two brown insets",
        "four brown disks",
        "fourth brown inset",
        "loose disk outside tile",
        "outside token",
        "farm",
        "road",
        "field",
        "bridge",
        "building",
        "dam",
        "buoy",
        "photoreal aerial landscape",
    ),
    "02-126": (
        "second red marker",
        "fourth island",
        "road",
        "causeway",
        "bridge",
        "pavilion",
        "pagoda",
        "temple",
        "shrine",
        "building",
        "stele",
        "glyph",
        "inscription",
        "photoreal aerial landscape",
    ),
    "02-129": (
        "fourth channel",
        "fourth groove",
        "branching groove",
        "network branches",
        "more than three grooves",
        "red seed pod",
        "chili pepper",
        "tail",
        "plant",
        "middle decoration",
        "engraved network",
        "branched engraving",
    ),
    "02-132": (
        "fourth sea channel",
        "fourth groove",
        "fourth shore block",
        "branching channel",
        "map label",
        "compass rose",
        "boat",
        "ship wake",
        "causeway",
        "bridge",
        "road",
        "pyramid",
        "building",
        "harbor",
        "photoreal aerial landscape",
    ),
    "02-133": (
        "fourth object",
        "second spearhead",
        "crown",
        "spear shaft",
        "wooden shaft",
        "pole",
        "handle",
        "complete spear",
        "side notch",
        "side cutout",
        "barbed spearhead",
        "modern broadhead",
        "paper",
        "page",
        "open bundle",
        "dark background",
        "dark red background",
        "black border",
        "vignette",
    ),
    "02-135": (
        "third channel",
        "third groove",
        "pavilion",
        "temple",
        "pagoda",
        "shrine",
        "building",
        "bridge",
        "causeway",
        "road",
        "red stele",
        "Chinese character",
        "Japanese character",
        "Korean character",
        "glyph",
        "inscription",
        "boat",
        "wake",
        "photoreal aerial landscape",
    ),
    "02-136": (
        "second sword",
        "four branches total",
        "four lateral branches",
        "two branches on left",
        "two branches on right",
        "eight branches total",
        "four branches on left",
        "four branches on right",
        "ten branches total",
        "five branches on left",
        "five branches on right",
        "five paired branch levels",
        "ladder-shaped sword",
        "menorah-shaped sword",
        "candelabrum sword",
        "detached hooks",
        "floating hooks",
        "loose hooks",
        "separate hook pieces",
        "branches clustered at top",
        "top crossguard cluster",
        "crown-shaped crossguard",
        "six hooks at one height",
        "hooks attached to horizontal bar",
        "five lateral branches",
        "seven lateral branches",
        "symmetric star",
        "four-point star",
        "X-shaped weapon",
        "mirrored branch pairs",
        "opposed branch pair",
        "bottom blade point",
        "pointed tang",
        "double-ended central blade",
        "branches meeting at one hub",
        "branches clustered at tang",
        "paired prongs at one height",
        "two prongs sharing one attachment point",
        "horizontal crossbar",
        "full-width horizontal bar",
        "paired crossguard bars",
        "branch crossing the spine",
        "extra side prong",
        "crossguard",
        "handle",
        "hilt",
        "pommel",
        "multiple weapons",
        "spear",
        "arrow",
        "bronze sword",
    ),
    "02-137": (
        "fourth object",
        "fourth cargo object",
        "fifth cargo object",
        "second bamboo bundle",
        "second craft strip",
        "human statue",
        "second boat",
        "paper",
        "page",
        "book",
        "Chinese character",
        "Korean character",
        "Japanese character",
        "writing",
        "glyph",
        "inscription",
        "tea kettle",
        "teapot",
        "spout",
        "lid",
        "goblet",
        "stemmed cup",
        "chalice",
        "modern tool kit",
        "tool bundle",
        "knife",
        "steel tool",
        "iron tool",
        "dark grey blade",
        "pointed blade",
        "tool grip",
        "bronze grip",
        "wooden tool handle",
        "handled chisel",
        "cutting knife",
        "second bronze bar",
        "loose rod",
        "cylindrical handle",
        "second source packet",
        "realistic wooden boat",
        "writing on boat hull",
        "marked boat hull",
        "second chisel",
        "second stone slab",
        "second ink slab",
        "inkstone",
        "stone slab",
        "marked cloth packet",
        "engraved ink slab",
        "picture on stone",
        "relief on stone",
        "seal mark",
    ),
    "02-138": (
        "fourth vessel",
        "modern sailboat",
        "Chinese junk",
        "junk ship",
        "galleon",
        "caravel",
        "steamship",
        "warship cannon",
        "second sail",
        "multiple sails",
        "triangular sail",
        "lateen sail",
        "mast forest",
        "high stern",
        "castle deck",
        "deckhouse",
    ),
    "02-139": (
        "second early boat",
        "second later boat",
        "realistic wooden rowboat",
        "three-dimensional boat",
        "open boat interior",
        "boat seats",
        "wooden planks",
        "oar",
        "arrow",
        "transition arrow",
        "infographic symbol",
        "equals sign",
        "sail",
        "mast",
        "galleon",
        "caravel",
        "European ship",
        "cannon",
        "high stern",
        "deckhouse",
        "black background",
        "dark frame",
        "vignette",
    ),
    "02-140": (
        "fourth channel",
        "fourth groove",
        "fourth bar",
        "four blue bars",
        "engraved groove",
        "X-shaped groove",
        "cross-shaped groove",
        "branching groove",
        "butterfly shape",
        "humanoid shape",
        "body shape",
        "genital shape",
        "teardrop seed",
        "seed-shaped token",
        "black background",
        "dark frame",
        "vignette",
    ),
    "02-141": (
        "second early boat",
        "fourth later ship",
        "fifth later ship",
        "realistic wooden rowboat",
        "three-dimensional boat",
        "open boat interior",
        "boat seats",
        "wooden planks",
        "oar",
        "square counter",
        "rectangular counter",
        "center groove",
        "black dividing line",
        "split panel",
        "diptych",
        "third era",
        "mast",
        "sail",
        "cabin",
        "roof",
        "deckhouse",
        "rail",
        "rope",
    ),
    "02-142": (
        "second early boat",
        "second later ship",
        "mast",
        "sail",
        "cabin",
        "roof",
        "deckhouse",
        "rail",
        "rope",
        "cross-shaped mast",
        "Christian cross",
    ),
    "02-144": (
        "fifth community marker",
        "crown",
        "king portrait",
        "green marker",
        "rimmed token",
        "coin",
        "Chinese character",
        "Korean character",
        "Japanese character",
        "glyph",
        "writing",
        "inscription",
        "symbol",
    ),
    "02-145": (
        "second red disk",
        "two red disks",
        "paired red disks",
        "extra red disk",
        "second kingdom disk",
        "two kingdom disks",
        "second hemp packet",
        "second brown packet",
        "paired hemp packets",
        "split hemp packet",
        "two brown packets",
        "fifth object",
        "fourth source bundle",
        "fourth source packet",
        "fifth source packet",
        "sixth source packet",
        "extra packet",
        "second bamboo bundle",
        "loose bamboo tube",
        "bamboo cylinder",
        "white modern pouch",
        "heat-sealed pouch",
        "open page",
        "book",
        "crest",
        "seal emblem",
        "coat of arms",
        "Chinese character",
        "Korean character",
        "Japanese character",
        "glyph",
        "writing",
        "inscription",
        "circular writing",
        "marked disk",
        "engraved disk",
        "decorated disk",
        "embossed disk",
        "carved glyph",
        "circular pattern",
        "central knob",
        "rimmed disk",
    ),
    "02-146": (
        "third founder disk",
        "three red disks",
        "unequal founder disks",
        "extra marker",
        "northbound path",
    ),
    "02-147": (
        "fourth object",
        "fourth clay piece",
        "fifth object",
        "second grey disk",
        "book",
        "codex",
        "packet",
        "bundle",
        "paper",
        "perforated disk",
        "hole in disk",
        "separated objects",
        "gap between objects",
        "Chinese character",
        "Korean character",
        "Japanese character",
        "glyph",
        "writing",
        "inscription",
        "wedding ring",
        "bride",
        "groom",
    ),
    "02-148": (
        "smooth circular community disk",
        "bullseye community disk",
        "concentric community rings",
        "inner red disk",
        "sixth community disk",
        "seventh community disk",
        "overlapping red disks",
        "stacked red disks",
        "loose red disks",
        "second community cluster",
        "empty boat tray",
        "realistic wooden boat",
        "fourth bundle",
        "fifth bundle",
        "second boat",
        "marked disk",
        "Chinese character",
        "Korean character",
        "Japanese character",
        "glyph",
        "writing",
        "inscription",
        "detailed boat",
        "mast",
        "sail",
        "cabin",
        "split panel",
        "diptych",
        "vertical divider",
        "black dividing line",
        "bullet list",
        "typography",
        "information card",
        "written explanation",
    ),
    "02-149": (
        "fifth source token",
        "repeated shape",
        "separated token",
        "gap between token and central disk",
        "writing",
        "glyph",
        "inscription",
    ),
    "02-150": (
        "fourth lineage disk",
        "fifth lineage disk",
        "top-row lineup",
        "three disks on one side",
        "split-color disk",
        "writing",
        "glyph",
    ),
    "02-151": (
        "fourth source bundle",
        "burned bundle",
        "erased bundle",
        "bamboo tube",
        "bamboo cylinder",
        "canister",
        "jar",
        "scroll",
        "book",
        "open paper",
        "writing",
        "glyph",
    ),
    "02-153": (
        "fourth wedge",
        "fourth lineage",
        "crown",
        "map",
        "continent",
        "Africa silhouette",
        "landmass",
        "country outline",
        "jigsaw",
        "cracked central disk",
        "central cutout",
        "clay shard",
        "arrow",
        "spearhead",
    ),
    "02-154": (
        "third object",
        "second disk",
        "black background",
        "dark background",
        "black border",
        "black outer frame",
        "letterbox",
        "vignette",
        "marked disk",
        "coin",
        "medallion",
        "Chinese character",
        "Korean character",
        "Japanese character",
        "glyph",
        "writing",
        "inscription",
    ),
    "02-155": (
        "only three rank blocks",
        "missing fourth rank block",
        "fifth rank block",
        "sixth rank block",
        "marked block",
        "concentric rings",
        "Chinese character",
        "Korean character",
        "Japanese character",
        "glyph",
        "writing",
        "king portrait",
    ),
    "02-156": (
        "only two brown blocks",
        "only three brown blocks",
        "missing third brown block",
        "missing fourth brown block",
        "third commandery tile",
        "extra grey tile",
        "large central grey tile",
        "shattered fragments",
        "loose grey shard",
        "giant central tile",
        "fifth Mahan block",
        "sixth Mahan block",
        "seventh Mahan block",
        "eighth Mahan block",
        "extra object",
        "battle scene",
    ),
    "02-157": (
        "decorated royal disk",
        "embossed royal disk",
        "rimmed royal disk",
        "central emblem",
        "concentric rings",
        "circular relief",
        "glossy lacquer lid",
        "coin-like royal disk",
        "only three rank blocks",
        "missing fourth rank block",
        "fifth rank block",
        "second spearhead",
        "second law tablet",
        "third law tablet",
        "blank square replacing spearhead",
        "pale tile at right",
        "modern law book",
        "dark background",
        "red background",
        "black border",
        "black outer frame",
        "vignette",
        "circular inscription",
        "Latin letters",
        "Chinese character",
        "Korean character",
        "Japanese character",
        "glyph",
        "writing",
        "coin",
        "medallion",
        "spear shaft",
        "wooden shaft",
        "handle",
        "hilt",
        "pole",
        "barbed spearhead",
        "fantasy spear",
    ),
    "02-158": ("fourth cloth swatch", "green cloth", "yellow cloth", "robe body", "mannequin"),
    "02-159": ("third authority disk", "social media icon", "play button", "thumb icon"),
}
